services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mathify
      - DB_USER=postgres
      - DB_PASSWORD_FILE=/run/secrets/db-password
    restart: on-failure

  db:
    image: postgres:16
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_DB=mathify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "mathify" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt